### ISSUE TITLE
ECMA 2015 language specification in epub and mobi

### ISSUE THREAD

**Issue by pferretti** [pferretti/docsforkindle#14]
Taken from http://www.ecma-international.org/ecma-262/6.0/index.html

**Comment by 5car1z** [comment]
#17

**Comment by pferretti** [comment]
Unfortunately the epub created from the PDF is poorly formatted and unreadable in most parts. I think that the HTML should be a better starting point.

**Comment by 5car1z** [comment]
Oops, I should have checked it more, sorry about that. Thought it was fine.

**Comment by pferretti** [comment]
Don't worry :-)

**Comment by 5car1z** [comment]
Hopefully someone with more experience using Calibre can come up with these (using the HTML). I only use the `ebook-convert` feature via command line that comes with it.
