### ISSUE TITLE
Docs for Django 1.10 in mobi format

### ISSUE THREAD

**Issue by pferretti** [pferretti/docsforkindle#4]

**Comment by HashCode55** [comment]
I'm on it.

**Comment by arpit1997** [comment]
Good job on this project. There is no [django 1.9](https://docs.djangoproject.com/en/1.9/contents/) docs in the repository. I guess it is skipped. I suggest to add the django 1.9 docs as it is the latest stable version available for django. 
One more suggestion which is a feature request is to add [flask](http://flask.pocoo.org/) docs too.
Thank yout :smile:

**Comment by pferretti** [comment]
Added issues for django 1.9 and flask :-)

**Comment by arpit1997** [comment]
Than you for that. Cool :smile: :smiley:
