### ISSUE TITLE
Add Django 1.9 docs in epub and mobi format

### ISSUE THREAD

**Issue by pferretti** [pferretti/docsforkindle#6]

**Comment by gilbertodurga** [comment]
I'll send a pr soon
You just need the official 1.9 docs in epub and mobi, that's it?

**Comment by 5car1z** [comment]
I got hold of the epub from https://docs.djangoproject.com/en/1.9/ and converted it to a mobi using Kindlegen. 

See PR #8 for both of these.

**Comment by pferretti** [comment]
It's ok, I accepted the pr
